# -*- coding: utf-8 -*-
"""Ai lab task 2-BSAI3-044.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14VcZZZc-59G_Wa0rBN10P_J0sXMw8gPX

#Mini project 1
"""

players=int(input("number of players: "))
print(f"there are {players} players playing.")
for i in range(1, players + 1):
  turn = i;
  print(f"player number {turn} is playing")
fizz_buzz()

def fizz_buzz():
 n=int(input("enter a number: "))
 if n%3==0 and n%5== 0:
    print("fizz buzz")
 elif n%3 ==0:
    print("fizz")
 elif n%5 ==0:
    print("buzz")
 else:
    if n%3!=0 or n%5!=0:
     print ("you're elminated")
if players:
 players=players-1
 print(f"now {players} are playing")
else:
 print(f"There are {players_count} players playing.")



fizz_buzz()

"""Mini project 2"""

movies = [
    ("Eternal Sunshine of the Spotless Mind", 20000000),
    ("Memento", 9000000),
    ("Requiem for a Dream", 4500000),
    ("Pirates of the Caribbean: On Stranger Tides", 379000000),
    ("Avengers: Age of Ultron", 365000000),
    ("Avengers: Endgame", 356000000),
    ("Incredibles 2", 200000000)
]

budgets=[budget for _, budget in movies]
total_budget=sum(budgets)
average_budget=(total_budget/len(budgets))
print(f"average_budget is {average_budget}")

count = 0

for name,budgets in movies:
  if budgets > average_budget:
    movie_budget = budgets - average_budget
    count = count + 1
    print(f"\n {count} Budget for {name} is {movie_budget} greater")